[workspace]
resolver = "2"
members = [
    "galileo",
    "galileo-mvt",
    "galileo-types",
]

exclude = [
    "wasm_examples/simple_map",
    "wasm_examples/vector_tiles",
    "wasm_examples/countries",
]