[package]
name = "galileo-mvt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
prost = "0.12.2"
galileo-types = { path = "../galileo-types" }
log = "0.4.20"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
nalgebra = { version = "0.32", features = ["serde-serialize"] }

[build-dependencies]
prost-build = "0.12.2"
